use_frameworks!

target 'KodexCoreNetwork-Test_Example' do
  pod 'KodexCoreNetwork-Test', :path => '../'

  target 'KodexCoreNetwork-Test_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
